name: mi_card_flutter
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/profilepic.png

  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf

    - family: Metrophobic
      fonts:
        - asset: fonts/Metrophobic-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: Permanent Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf